config:
  outputs: |
    [OUTPUT]
        Name s3
        Match kube.*
        bucket ${AWS_S3_BUCKET}
        region us-east-2
        total_file_size 1M
        upload_timeout 1m
        use_put_object On
        s3_key_format /k3s-logs/${WORKFLOW_RUN_ID}/$TAG/%Y/%m/%d/%H/%M
