datasources:
  config:
    connection-test-query: SELECT 1
    connection-timeout: 30000
    maximum-pool-size: 10
    minimum-pool-size: 0
    url: ${DATABASE_URL}
    driverClassName: org.postgresql.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

flyway:
  enabled: true
  datasources:
    config:
      enabled: false
      locations:
        - 'classpath:io/airbyte/db/instance/configs/migrations'
    jobs:
      enabled: false
      locations:
        - 'classpath:io/airbyte/db/instance/jobs/migrations'

jooq:
  datasources:
    config:
      jackson-converter-enabled: true
      sql-dialect: POSTGRES
    jobs:
      jackson-converter-enabled: true
      sql-dialect: POSTGRES
